import { LeaderboardUser } from './../../constants/types'

export const users: LeaderboardUser[] = [
  {
    uid: '',
    highlightedUser: false,
    rank: 1,
    name: 'Kenan Casey',
    avgGuesses: 2,
    points: 1000,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 2,
    name: 'Dallas Yarnell',
    avgGuesses: 3.5,
    points: 900,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 3,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 800,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 4,
    name: 'Anonymous Joe',
    avgGuesses: 2,
    points: 700,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 5,
    name: 'Anonymous Joe',
    avgGuesses: 3.5,
    points: 650,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 6,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 600,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 7,
    name: 'Anonymous Joe',
    avgGuesses: 2,
    points: 500,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 8,
    name: 'Anonymous Joe',
    avgGuesses: 3.5,
    points: 400,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 9,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 400,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 10,
    name: 'Anonymous Joe',
    avgGuesses: 2,
    points: 350,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 11,
    name: 'Anonymous Joe',
    avgGuesses: 3.5,
    points: 350,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 12,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 300,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 13,
    name: 'Anonymous Joe',
    avgGuesses: 2,
    points: 300,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 14,
    name: 'Anonymous Joe',
    avgGuesses: 3.5,
    points: 300,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 15,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 250,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 16,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 250,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 17,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 200,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 18,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 200,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 19,
    name: 'Kaden King',
    avgGuesses: 5,
    points: 100,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 20,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 50,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 21,
    name: 'Kenan Casey',
    avgGuesses: 2,
    points: 1000,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 22,
    name: 'Dallas Yarnell',
    avgGuesses: 3.5,
    points: 900,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 23,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 800,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 24,
    name: 'Anonymous Joe',
    avgGuesses: 2,
    points: 700,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 25,
    name: 'Anonymous Joe',
    avgGuesses: 3.5,
    points: 650,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 26,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 600,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: true,
    rank: 27,
    name: 'Anonymous Joe',
    avgGuesses: 2,
    points: 500,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 28,
    name: 'Anonymous Joe',
    avgGuesses: 3.5,
    points: 400,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 29,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 400,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 30,
    name: 'Anonymous Joe',
    avgGuesses: 2,
    points: 350,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 31,
    name: 'Anonymous Joe',
    avgGuesses: 3.5,
    points: 350,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 32,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 300,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 33,
    name: 'Anonymous Joe',
    avgGuesses: 2,
    points: 300,
    lastPlayed: '',
    stats: {
      currentStreak: 10,
      bestStreak: 10,
      successRate: 100,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 34,
    name: 'Anonymous Joe',
    avgGuesses: 3.5,
    points: 300,
    lastPlayed: '',
    stats: {
      currentStreak: 7,
      bestStreak: 8,
      successRate: 80,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 35,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 250,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 36,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 250,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 37,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 200,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 38,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 200,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 39,
    name: 'Kaden King',
    avgGuesses: 5,
    points: 100,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
  {
    uid: '',
    highlightedUser: false,
    rank: 30,
    name: 'Anonymous Joe',
    avgGuesses: 5,
    points: 50,
    lastPlayed: '',
    stats: {
      currentStreak: 3,
      bestStreak: 5,
      successRate: 60,
    },
  },
]
